version: 0.1.0
editor: claude-code
local:
  patterns:
    - "**/*.ctx.md"
    - "**/ctx.md"
  ignore:
    - node_modules/**
    - dist/**
    - build/**
    - .git/**
global:
  directory: ctx
  patterns: "**/*.md"
  ignore: []
